name: breather
description: Breather - Quarantine Party app
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_rounded_date_picker: ^1.0.4
  flutter_circular_slider:
  sleek_circular_slider:
  flutter_localizations:
    sdk: flutter
  percent_indicator: ^2.1.3
  flutter_dotenv: ^2.1.0
  lottie: ^0.3.3
  google_nav_bar: ^2.2.0
  intl: ^0.16.1
  sqflite: ^1.3.0+1
  path_provider: ^1.6.8
  json_annotation: ^3.0.1
  rolling_nav_bar: ^0.0.1
  flutter_mobx:
  provider:
  mobx:

dev_dependencies:
  flutter_native_splash: ^0.1.9
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
  mobx_codegen:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/animations/
   - .env
  fonts:
    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-Regular.ttf
        - asset: assets/fonts/RobotoSlab-Thin.ttf
          weight: 100
        - asset: assets/fonts/RobotoSlab-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/RobotoSlab-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoSlab-Regular.ttf
          weight: 400
        - asset: assets/fonts/RobotoSlab-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoSlab-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/RobotoSlab-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoSlab-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/RobotoSlab-Black.ttf
          weight: 900
  